### ISSUE TITLE
Make Flatpak package

### ISSUE THREAD

**Issue by HACKERALERT** [Picocrypt/Picocrypt#18]

**Comment by HACKERALERT** [comment]
https://docs.flatpak.org/en/latest/first-build.html

**Comment by HACKERALERT** [comment]
Realistically tho, with a raw Linux binary and a .deb, do we really need a flatpak?

**Comment by hakavlad** [comment]
Fedora users love flatpak.

**Comment by theuser18** [comment]
It would allow for its release on flathub, if you want that.

I would like it so it can be updated via my distro's software center. I also appreciate flatpak's sandboxing.

**Comment by Retengart** [comment]
I tried to create a manifest file to build a Flatpak package. I confirmed that Picocrypt is working as expected. However, there is one issue: the application icon is not being displayed.
```yaml
app-id: com.github.Picocrypt
runtime: org.freedesktop.Platform
runtime-version: "22.08"
sdk: org.freedesktop.Sdk
command: picocrypt-gui
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --device=dri
  - --filesystem=home
modules:
  - name: picocrypt
    buildsystem: simple
    build-commands:
      - bsdtar --to-stdout -xf Picocrypt.deb data.* | bsdtar -xf -
      - mv usr/bin /app/
      - chmod +x /app/bin/picocrypt-gui
      - cp -a usr/share /app/
      - rm usr/share/applications/picocrypt.desktop
      - mv usr/share/icons/picocrypt.svg /app/com.github.Picocrypt.svg
      - touch /app/com.github.Picocrypt.desktop
      - echo "[Desktop Entry]" >> /app/com.github.Picocrypt.desktop
      - echo "Name=Picocrypt" >> /app/com.github.Picocrypt.desktop
      - echo "Comment=Secure file encryption tool" >> /app/com.github.Picocrypt.desktop
      - echo "Exec=picocrypt-gui" >> /app/com.github.Picocrypt.desktop
      - echo "Icon=com.github.Picocrypt" >> com.github.Picocrypt.desktop
      - echo "Type=Application" >> /app/com.github.Picocrypt.desktop
      - echo "Categories=Utility;Security;" >> /app/com.github.Picocrypt.desktop
      - install -Dm644 /app/com.github.Picocrypt.desktop /app/share/applications/com.github.Picocrypt.desktop
      - install -Dm644 /app/com.github.Picocrypt.svg /app/share/icons/hicolor/scalable/apps/com.github.Picocrypt.svg
    sources:
      - type: file
        url: https://github.com/Picocrypt/Picocrypt/releases/latest/download/Picocrypt.deb
        sha256: a7525a21a81647e8d56bc99ba7c8fa298971c82bde4923972186fa8766a19026
    cleanup:
      - share/applications/picocrypt.desktop
      - share/icons/picocrypt.svg
      - Picocrypt.deb
```

**Comment by HACKERALERT** [comment]
Does using Icon=com.github.Picocrypt.svg (added .svg) work?

**Comment by HACKERALERT** [comment]
This is really cool stuff so far, thanks! Is 22.08 the latest?

**Comment by HACKERALERT** [comment]
Btw the .deb typically installs dependency packages like libgcc-s1. Is that also needed here?

**Comment by HACKERALERT** [comment]
What's the output? A flatpakref or something like that? Wondering how users would use it to install the app.

**Comment by Retengart** [comment]
> This is really cool stuff so far, thanks! Is 22.08 the latest?

As a result, I figured out the icon, and I will soon present a new version. As for the freedesktop version 22.08, I think it doesn't matter here, because for Flatpack there should usually be a runtime, even if the application itself is self-sufficient. 22.08 is the stable version of freedesktop (there is a beta 23.08 or master branch)

**Comment by Retengart** [comment]
Now the regular Picocrypt binary is used to build Flatpak, not Picocrypt.deb. The Picocrypt ID is now the following: io.github.Picocrypt (based on the recommendation of the Flatpak manual). org.freedesktop.Platform is selected on 22.08 (I think most of those who use Flatpak will already have it installed, if not, then the second picocrypt.flatpak with freedesktop 23.08 will also be published/edited in release 1.42. 
So far, the link to io.github.Picocrypt.metainfo.xml is from my fork.

```yaml
app-id: io.github.Picocrypt
runtime: org.freedesktop.Platform
runtime-version: "22.08"
sdk: org.freedesktop.Sdk
command: picocrypt-gui
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --filesystem=home
modules:
  - name: picocrypt-gui
    buildsystem: simple
    build-commands:
      - touch io.github.Picocrypt.desktop
      - echo "[Desktop Entry]" >> io.github.Picocrypt.desktop
      - echo "Name=Picocrypt" >> io.github.Picocrypt.desktop
      - echo "Comment=Secure file encryption tool" >> io.github.Picocrypt.desktop
      - echo "Type=Application" >> io.github.Picocrypt.desktop
      - echo "Exec=picocrypt-gui" >> io.github.Picocrypt.desktop
      - echo "Icon=io.github.Picocrypt" >> io.github.Picocrypt.desktop
      - echo "Categories=Utility;Security;" >> io.github.Picocrypt.desktop
      - install -Dm755 Picocrypt /app/bin/picocrypt-gui
      - install -Dm644 io.github.Picocrypt.desktop /app/share/applications/io.github.Picocrypt.desktop
      - install -Dm644 key.svg /app/share/icons/hicolor/scalable/apps/io.github.Picocrypt.svg
      - install -Dm644 io.github.Picocrypt.metainfo.xml /app/share/metainfo/io.github.Picocrypt.metainfo.xml
    sources:
      - type: file
        url: https://github.com/Picocrypt/Picocrypt/releases/download/1.42/Picocrypt
        sha256: 7112b72d0b62337f9249e47f6079b8a041c445fc089f0610ca3af040514e4ab2
      - type: file
        url: https://raw.githubusercontent.com/Picocrypt/Picocrypt/main/images/key.svg
        sha256: f2f3b9ad8322d8e0d9bc3ba888fa89310bfe54800f48d53a4260c71c96f79cf6
      - type: file
        url: https://raw.githubusercontent.com/Retengart/PicoDwarFS/metainfo/io.github.Picocrypt.metainfo.xml
        sha256: c8b5504d4e972af181ba767442ae32b5999c0c69340fb543807ce93a980ed5fc
```

To build and install from the manifest:
```bash
flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install builddir io.github.Picocrypt.yml
```
To bundle into .flatpak:
```bash
flatpak build-bundle repo Picocrypt.flatpak io.github.Picocrypt --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
```
To install from flatpak package:
```bash
flatpak install --user Picocrypt.flatpak
```

**Comment by Retengart** [comment]
As soon as I edit metainfo.xml , I will send a PR

**Comment by HACKERALERT** [comment]
Try to include any assets like the xml in this repo so there's nothing external. Just for best practice. Do I also need to publish this to flathub? Been a snapcraft builder for a while, not sure how flatpaks work in detail.

**Comment by HACKERALERT** [comment]
Can you also include environment variables as specified in src/README? Namely LIBGL_ALWAYS_SOFTWARE and NO_AT_BRIDGE I think.

Also the dependencies you need to install, like libgcc-s1, libgl1, etc., is there a way to specify those?

**Comment by Retengart** [comment]
> Can you also include environment variables as specified in src/README? Namely LIBGL_ALWAYS_SOFTWARE and NO_AT_BRIDGE I think.
> 
> Also the dependencies you need to install, like libgcc-s1, libgl1, etc., is there a way to specify those? I also think there's a gtk3 runtime or something for flatpaks, may be useful as the file saver/picker depends on gtk3.

Unfortunately, there are only four runtimes for Flatpak: freedesktop, GNOME, KDE, elementary. It is impossible to use anything else. 
As for dependencies, I'm not sure that they need to be added here, in theory freedesktop can sort everything out in this case (I tested the flatpak package in a fresh virtual machine with Lubuntu, I didn't find any problems).
About assets, yeah, link from my fork is temporarily. The future link will be from https://raw.githubusercontent.com/Picocrypt/Picocrypt/main/flatpak/io.github.picocrypt.Picocrypt.metainfo.xml

**Comment by HACKERALERT** [comment]
Awesome. Can you add this:

org.freedesktop.Platform.GL{,32}.default

As the app needs OpenGL.

I'll try to setup GitHub actions for this when you have a stable setup.

**Comment by Retengart** [comment]
> Awesome. Can you add this:
> 
> org.freedesktop.Platform.GL{,32}.default
Added, so there is the pull request

**Comment by HACKERALERT** [comment]
Thanks.

Relevant: https://docs.flathub.org/docs/for-app-authors/submission/

I'll try to fork sometime and maybe the files should go there?

**Comment by HACKERALERT** [comment]
https://github.com/fyne-io/flatpak_demo/blob/main/io.fyne.flatpak_demo.yml

May be relevant

**Comment by Retengart** [comment]
> https://github.com/fyne-io/flatpak_demo/blob/main/io.fyne.flatpak_demo.yml
> 
> May be relevant

Thanks, I'll try it instead "installing the binary"
```yaml
app-id: io.github.picocrypt.Picocrypt
runtime: org.freedesktop.Platform
runtime-version: "23.08"
sdk: org.freedesktop.Sdk
command: picocrypt-gui
finish-args:
- --share=ipc
- --socket=fallback-x11
- --socket=wayland
- --device=dri
- --filesystem=home
modules:
- name: picocrypt-gui
  buildsystem: simple
  build-commands:
  - install -Dm755 Picocrypt /app/bin/picocrypt-gui
  - install -Dm644 io.github.picocrypt.Picocrypt.svg /app/share/icons/hicolor/scalable/apps/io.github.picocrypt.Picocrypt.svg
  - install -Dm644 io.github.picocrypt.Picocrypt.desktop /app/share/applications/io.github.picocrypt.Picocrypt.desktop
  - install -Dm644 io.github.picocrypt.Picocrypt.metainfo.xml /app/share/metainfo/io.github.picocrypt.Picocrypt.metainfo.xml
  sources:
  - type: file
    url: https://github.com/Picocrypt/Picocrypt/releases/download/1.42/Picocrypt
    sha256: 7112b72d0b62337f9249e47f6079b8a041c445fc089f0610ca3af040514e4ab2
  - type: file
    path: io.github.picocrypt.Picocrypt.svg
    sha256: f2f3b9ad8322d8e0d9bc3ba888fa89310bfe54800f48d53a4260c71c96f79cf6
  - type: file
    path: io.github.picocrypt.Picocrypt.metainfo.xml
    sha256: efc8dccaa179306b90748f0a2b9a1f7be1aaf55d8f5bb4e642bdfb82827a2013
  - type: file
    path: io.github.picocrypt.Picocrypt.desktop
    sha256: 97110a23f8b74566e8c46dcddc216c9ec97aee7c6922f1a00df46d547bb544a0
```
